### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by vincenzoiovino** [ecies/rs#108]
Hi,
Do you think there is hope that this implementation can be compatible with bouncycastle's implementation(s) of ECIES?
Precisely, the goal would be to instantiate ECIES in BC so that the resulting ciphertexts would have the same format as yours (the BC ciphertexts are decryptable in your implementation and viceversa).
The reason is that I need compatibility among different frameworks like Android apps, Windows desktop Apps, web browsers, etc. With BC I can cover most of cases but it would be preferable to use yours to cover websites but before digging into details I would like to ask you an opinion on whether you deem easy to make them compatible each other. 
Thanks in advance

**Comment by cryptoquick** [comment]
Can you link to what you're describing?

**Comment by kigawas** [comment]
It's just concatenated bytes, there's no special "format". The standard payload is below:

```
+-------------------------------+----------+----------+-----------------+
| 65 Bytes                      | 16 Bytes | 16 Bytes | == data size    |
+-------------------------------+----------+----------+-----------------+
| sender_pk                     | nonce    | tag      | encrypted_data  |
+-------------------------------+----------+----------+-----------------+
|           Secp256k1           |              AES-256-GCM              |
+-------------------------------+---------------------------------------+
```

65 bytes pk can be 33 bytes with configuration. If you use x25519 or XChaCha20, pk or nonce length will be different.

**Comment by kigawas** [comment]
You have to take care of HKDF. I'm not sure how bouncycastle is doing, basically to get a common shared secret we have to use HKDF, say:

1. HKDF(Secp256k1 compressed shared key)
2. HKDF(Secp256k1 uncompressed shared key)

We are using standard HKDF-SHA256. If bc is using HKDF-SHA512, it'll not be compatible

**Comment by kigawas** [comment]
Another important thing is that you have to take care of HKDF. I'm not sure how bouncycastle is doing, basically to get a common shared secret we have to use HKDF (since simple hash functions are not secure enough), like `HKDF(Secp256k1 compressed/uncompressed shared key)`.

We are using standard HKDF-SHA256. If bc is using HKDF-SHA512 or something else, it'll not be compatible.

**Comment by vincenzoiovino** [comment]
I will look at that in next weeks.
Bouncycastle takes an abstract approach and allows you to instantiate all components (hash, hkdf, stream cipher, etc.) to your like so hopefully it should be possible to achieve compatibility. 
Thanks for all
