### ISSUE TITLE
Issue with `thiserror`

### ISSUE THREAD

**Issue by cryptoquick** [ecies/rs#111]
We can't seem to get past this error when updating past 0.2.4-- Versions 0.2.5 and 0.2.6 break with this error:

```rust
error[E0599]: the method `as_dyn_error` exists for reference `&SecpError`, but its trait bounds were not satisfied
 --> /home/hunter/.cargo/registry/src/index.crates.io-6f17d22bba15001f/carbonado-0.3.3/src/error.rs:3:10
  |
3 | #[derive(Error, Debug)]
  |          ^^^^^ method cannot be called on `&SecpError` due to unsatisfied trait bounds
  |
 ::: /home/hunter/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsecp256k1-core-0.3.0/src/error.rs:2:1
  |
2 | pub enum Error {
  | --------------
  | |
  | doesn't satisfy `SecpError: AsDynError<'_>`
  | doesn't satisfy `SecpError: StdError`
  |
  = note: the following trait bounds were not satisfied:
          `SecpError: StdError`
          which is required by `SecpError: AsDynError<'_>`
          `&SecpError: StdError`
          which is required by `&SecpError: AsDynError<'_>`
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The code in question uses a crate called `thiserror` to proxy error details:
https://github.com/diba-io/carbonado/blob/518188593fc2a86bf2fa687f9165b83904c0d64f/src/error.rs#L33-L35

Any idea what might be happening?

**Comment by kigawas** [comment]
This is related with libsecp256k1's error: https://github.com/paritytech/libsecp256k1/blob/master/core/src/error.rs#L14

You may need to enable "std" feature

**Comment by cryptoquick** [comment]
That fixed it! I would recommend adding `libsecp256k1/std` to the std features of this library so we don't have to specify it separately.

**Comment by kigawas** [comment]
It's optional so I'm afraid you have to enable `libsecp256k1/std` manually (i.e adding it to `std` will introduce libsecp256k1 on features `["x25519", "std"]`)
