### ISSUE TITLE
Zeroize on SecretKey

### ISSUE THREAD

**Issue by muellpanda** [ecies/rs#117]
I am unsure if this crate overwrites the memory where a SecretKey resides when its lifetime ends.
Overwriting it with zeroes would be one way to to this.
The idea here of course is to disable reading the secret from memory, after it is no longer needed.

Is this possible or planned?

**Comment by kigawas** [comment]
Only &[u8] is used and `SecretKey` and `PublicKey` are from `libsecp256k1`.
IMO zeroizing the secret key is not in our scope.
