### ISSUE TITLE
support `no_std`

### ISSUE THREAD

**Issue by yeti-g** [ecies/rs#80]
It would be very nice to support environments without standard library. Embedded devices like `target=thumbv6m-none-eabi` need `no_std`

```
$ cargo build --no-default-features --features pure --target=thumbv6m-none-eabi
   Compiling subtle v2.4.1
   Compiling base64 v0.13.0
   Compiling getrandom v0.2.3
   Compiling generic-array v0.14.4
   Compiling serde v1.0.131
error[E0463]: can't find crate for `std`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.4.1/src/lib.rs:88:1
   |
88 | extern crate std;
   | ^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: the `thumbv6m-none-eabi` target may not support the standard library

error[E0463]: can't find crate for `std`
 --> /.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/error_impls.rs:9:1
  |
9 | extern crate std;
  | ^^^^^^^^^^^^^^^^^ can't find crate
  |
  = note: the `thumbv6m-none-eabi` target may not support the standard library

For more information about this error, try `rustc --explain E0463`.
error: could not compile `subtle` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not support the standard library
  = note: `std` is required by `base64` because it does not declare `#![no_std]`

error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not support the standard library
  = note: `std` is required by `serde` because it does not declare `#![no_std]`

error: build failed
```

**Comment by kigawas** [comment]
Can you try this branch? https://github.com/ecies/rs/tree/no-std

I'm not sure if it can work, but it compiles on thumbv6m-none-eabi

**Comment by yeti-g** [comment]
Nice progress and a very cool project! I cannot test in my environment due to no heap memory or alloc support but you could probably close this issue as I took another approach to encryption in my embedded project. Fwiw I'm using [Heapless::Vec](https://github.com/japaric/heapless) in the project and it could be an easy change here if you choose to expand support for embedded devices.

**Comment by kigawas** [comment]
I've almost finished adding `no_std` support, but the random generator is a problem. Only targets below are supported and unfortunately `thumbv6m-none-eabi` is not one of them 😢 

https://docs.rs/getrandom/latest/getrandom/#supported-targets
